name: jet_set_go
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0      # For selecting files (PDFs, images)
  image_picker: ^1.0.7     # For taking pictures
  path_provider: ^2.1.2    # For saving files locally
  pdf: ^3.10.6             # For generating PDFs from images
  open_file: ^3.3.2        # To open/view saved documents
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  logger: ^2.5.0
  permission_handler: ^11.3.1
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  flutterfire_cli: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/background.png
    - assets/app bar background.png
    - assets/plane pattern.png
    - assets/takeoff-the-plane 2.png
    - assets/Line 1.png
    - assets/reduced mobility passenger.jpg
    - assets/pregnant passenger.jpg
    - assets/travelling with children.webp
    - assets/unaccompanied minor.webp
    - assets/elder Passenger.jpg
    - assets/images/
    - assets/packing_bg.jpg
    - assets/luggage.jpg
    - assets/app_bar_bg.jpg
    - assets/background.jpg
    - assets/line.jpg
    - assets/plane_bg.jpg
    - assets/plane_icon.jpg
    - assets/header.jpg
    - assets/headerIcon.jpg
    - assets/plane.png
