name: Dart & Flutter CI

on:
  push:
    branches: [ "main" , "development" ]
  pull_request:
    branches: [ "main" , "development" ]
  workflow_dispatch: # ✅ Allows manual execution from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'

      # ✅ Enable cache to speed up builds
      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            flutter-pub-cache-${{ runner.os }}-

      # ✅ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # ✅ Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # ✅ Run tests (if applicable)
      #- name: Run tests
      #  run: flutter test
